language: clojure
lein: lein2
env:
  global:
  - secure: FJUAoxZj9wc2i4B34aHW2j6s95jmBW7gZcDjW2IMZ/SjVR7w/EEd2hlhS00Lsh+mURPZ08bWXGW+lL2ndl+gumZkI5qITeCcJ8Gz5+cvU+nfeH1cBYWCP80VbNEkv7uykmLRCM1wRgsznGPbp4B/yPCHPNwr9N+JC4sDXV73FcE=
  - secure: kk3lA4LlOim06r5oec4cqA/vY1eKid6rG6lQpn5hHFXqq0BC4dbO3ELHkAPw56a0LKyrGBjHfbRpDRpozE3x6rbJSl0P55txwQhDwye6dP3NAv+MM0z31EYqYUvTRHCeLybw/1p2KgiaXU9RhAIb2mMarKCAIKZZZ9hVeGqZouY=
  - secure: OIy9yo/vB9cIG0GkZB+L3TFy08N0E1/MnZPmA30wykvUkZ/BS1O/jlAfI/MYyGOj+Y5DXKJ+UGO7nU1+Adyl4G7HzbbAMSv5bj2oWv9Ixu5lzohZaatT0+5UBL7Sr9IDnITdBpvbcNLu8YfLaZKRdNt2xwsj6ZCuRZLb2mKYEkQ=
  - secure: NprW30FiR4TwBcjfRck3VCfM3ul1WFRrTjVku5lAa+re8UCA3DeQt/ZWHRTQ1CVB5qUHixMI1aHsTY6RLluybc7NFl5BIosHTH7an211nLPxWugVL6WlA/F7ACf1/affxWeUU5TgLkpNGhjn3414swNVUIieERLuJRny8Vn1kkc=
install: sudo apt-get install expect
script: lein2 with-profile dev misaki --compile
after_success: bin/deploy.sh
jdk:
- oraclejdk7
