language: clojure
lein: lein2
env:
  global:
  - secure: RNnQ26d+BjNDnk89Wh+XrAmkElGmbZ+aQexHuvhNQIlMAScAtZrl3Rso+n5dX84ObxPU+XOlCI4niXAfWwwPUSvzhkq9rTAt0GD/X3fctzCH+yLv0rG8ooKFeR47jk5b0IBmCOnu/7Zmg56vhw7v6DjhZkPwcdYLj430o9AOthg=
  - secure: U4OcTE2w1qXVGbMq7sNgx4NKHwaveL/92RQC+Q3hv3bw0pepTgguEzz5GWciC5x0Vhdl0E2ovmYZvWZinO0wBZCrusAJe9fjxuMtbOhzPzWVR6Suw630WBftG0oNav+ZhbLovcvKJk+FvM4AfZ7OZn4M8pQEug4+Mm6Dd2PAPm8=
  - secure: GBn/zvk40ak/TVVQQv73NyDanabDY+GXDkA97Cska3lFq9qwsVT8lpbBGCU337hls/IYSltf3jW9nzmxvMkr/jy/aGuYgi6xy7vyIIeF4FT+pw4+TdyuATkdsSwMz3yaul27D1RRK9c5AbCc6wIYV8anbUeKsVpNtPJ+Na5Wv1c=
  - secure: Qbel42TL0vdWW3dScK2JYMQ5crB29GRS7PXUxNu3CHa1xj2SKpZQwEo/j5C21NGfgCWTwuKZ16tSJJJCUUBi/sQLBIJ7KyyYgVAhMKLV+H0Lzz5xfhqSLFH/3+Rg0Rvowr0Lpw63f6PBuqZbVlxnc9mMerAA6v1Wcv9a1Cx+CNk=
install: sudo apt-get install expect
script: lein2 with-profile dev misaki --compile
after_success: bin/deploy.sh
jdk:
- oraclejdk7
