language: node_js
env:
  global:
  - secure: OyZdlXDoj1I7onIJSIvXlUYObXaAbed62dtiWq5K308t6h+kySg6x+9WeRQCJ9h24Mm6hcNikfSx57Cvl7DiDY75fU0y8tm74/t4WcRTqWmBtwcvG/YNv3RRXRrXFzpgFo2Np0NC++/MG0WamCyDuQaxAULbz8ixyuai03O2Ikc=
  - secure: Z3gQj7PSSJBx223aihlWwggdyYhiey1DzJvm/EO5Ten5uQY4gmGfJGdSI/C1hjudITyMj/fj7xnKzCSXioEnw2RngKR8yNiQfkNVHxAg0jDNAbwYbnRU/k7giZtWigCCx4M0uwDj4CHYGxTDHihjW0F+R3zxOjqM2ZAA9z9f234=
  - secure: kcO+yR9yQbn5LwbFUoGqvOQeFzVxCtSfaAxuzMHUFtf8FMtYSEyPwVb3N/LLqTla5JVdq8SXEE7ZBDDAA2KIJWpI4OyP4fGPyiYuIjjZy+TsIbgO+LSJr54PvU9MVkMzRFwdSBWAD1Kbf0XsSDoOgp+DuSSzACW8jn9qwKSLSgk=
branches:
  only:
  - master
before_install:
- nvm install stable
- nvm use stable
- npm install -g hexo
- npm install
install:
- hexo generate
addons:
  ssh_known_hosts: kanyid.org
before_deploy:
- openssl aes-256-cbc -K $encrypted_f2c96cf7f6c1_key -iv $encrypted_f2c96cf7f6c1_iv
  -in .travis/deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet ${TRAVIS_BUILD_DIR}/public ${DEPLOY_USERNAME}@${DEPLOY_HOST}:${DEPLOY_REMOTEDIR}
  on:
    branch: master
